repos:
  - repo: local
    hooks:
      - id: tfsec
        name: tfsec security scan
        entry: bash
        args:
          - -c
          - 'docker run --rm -v "$(pwd):/data" aquasec/tfsec /data'
        language: system
        pass_filenames: false
        files: \.tf$


  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt
      # - id: terraform_validate
      # - id: terraform_docs
      # - id: terraform_tflint
